### PR TITLE
Support for different forward and backward step size

### PR DESCRIPTION
**Pull request by Inrego**
I think if you just accept all commits from the pull request, it should be fine. Most of the commits are already in the repo, and the final code files are the same. Or else I guess they will be in every single PR I make from now on.

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
New properties for different step size for backward and forward steps.

### :arrow_heading_down: What is the current behavior?
A single property controls both forward and backward.

### :new: What is the new behavior (if this is a feature change)?
One property controls forward step size, another for backward.

### :boom: Does this PR introduce a breaking change?
Yes. `IMediaManager.StepSize` is now obsolete, and causes an error which redirects people to the new properties `StepSizeForward` and `StepSizeBackward`.

### :bug: Recommendations for testing
I've added 2 lines of code in `HomeViewModel` that sets these properties. They're commented out at the moment.
Note: the Forms iOS sample reverts to 15 and 15 for both after 1-2 seconds of playback. I'm unsure why, and I'm pretty sure it's unrelated to my changes. The other iOS sample works fine.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines 
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Inrego** [comment]
Any hold-ups keeping this from being merged?

**Comment by Inrego** [comment]
Should've made another branch for the Apple Queue changes so they could be a separate PR. But here we are, I guess ^^ You're welcome to merge that change as well if you agree with it.

**Comment by martijn00** [comment]
@Inrego can you open a seperate PR for the Apple Queue changes? It was too hard for me to figure things out from this PR, so i just merged the step size changes for now, and released that.

**Comment by Inrego** [comment]
Yup I will. I'll wait a bit, until I'm sure that I've ironed out all the bugs.

**Pull request closed without merging**
